"""removing daily 

Revision ID: 47cbd72b4d20
Revises: b12f36247eed
Create Date: 2023-09-27 13:09:01.305896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cbd72b4d20'
down_revision = 'b12f36247eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_column('average_day_feeling')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_day_feeling', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
