"""changing tables

Revision ID: 945a3f2fe8b4
Revises: 47cbd72b4d20
Create Date: 2023-09-28 17:34:56.478172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945a3f2fe8b4'
down_revision = '47cbd72b4d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('walk', sa.Integer(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activities')
    op.drop_table('feelings')
    op.drop_table('days')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_entry_id_entries'), 'entries', ['entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_entry_id_entries'), type_='foreignkey')
        batch_op.drop_column('entry_id')

    op.create_table('days',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feeling_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='fk_days_activity_id_activities'),
    sa.ForeignKeyConstraint(['feeling_id'], ['feelings.id'], name='fk_days_feeling_id_feelings'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feelings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('morning_feeling', sa.INTEGER(), nullable=True),
    sa.Column('afternoon_feeling', sa.INTEGER(), nullable=True),
    sa.Column('evening_feeling', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activity', sa.VARCHAR(), nullable=True),
    sa.Column('activity_status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entries')
    # ### end Alembic commands ###
