"""removing weekly 

Revision ID: b12f36247eed
Revises: bf8a50f67c33
Create Date: 2023-09-27 12:15:11.512008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12f36247eed'
down_revision = 'bf8a50f67c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_column('average_weekly_feeling')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_weekly_feeling', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
