"""adadding to day model

Revision ID: bf8a50f67c33
Revises: 33ae564bea85
Create Date: 2023-09-27 12:12:44.413878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8a50f67c33'
down_revision = '33ae564bea85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_day_feeling', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_weekly_feeling', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_column('average_weekly_feeling')
        batch_op.drop_column('average_day_feeling')

    # ### end Alembic commands ###
